tipos2:	tipos2.o
	g++ tipos2.o -o tipos2

tipos2.o:	tipos2.s
	as -g -o tipos2.o tipos2.s

tipos3a:	tipos3a.o
	g++ tipos3a.o -o tipos3a

tipos3a.o:	tipos3a.s
	as -g -o tipos3a.o tipos3a.s

tipos3b:	tipos3b.o
	g++ tipos3b.o -o tipos3b

tipos3b.o:	tipos3b.s
	as -g -o tipos3b.o tipos3b.s
	
tipos4:	tipos4.o
	g++ tipos4.o -o tipos4

tipos4.o:	tipos4.s
	as -g -o tipos4.o tipos4.s
	
tipos6:	tipos6.o
	g++ tipos6.o -o tipos6

tipos6.o:	tipos6.s
	as -g -o tipos6.o tipos6.s

clean:
	rm tipos2.o tipos2 tipos3a.o tipos3a tipos3b.o tipos3b tipos4.o tipos4 tipos6.o tipos6
