subrut1: subrut1.o
	g++ subrut1.o -o subrut1

subrut1.o: subrut1.s
	as -g -o subrut1.o subrut1.s

subrut2: subrut2.o
	g++ subrut2.o -o subrut2

subrut2.o: subrut2.s
	as -g -o subrut2.o subrut2.s
	
subrut3: subrut3.o
	g++ subrut3.o -o subrut3

subrut3.o: subrut3.s
	as -g -o subrut3.o subrut3.s

subrut5: subrut5.o
	g++ subrut5.o -o subrut5

subrut5.o: subrut5.s
	as -g -o subrut5.o subrut5.s
	
clean:
	rm subrut1.o subrut1 subrut2.o subrut2 subrut3.o subrut3 subrut5.o subrut5
