tipos2:	tipos2.o
	g++ tipos2.o -o tipos2

tipos2.o:	tipos2.s
	as -g -o tipos2.o tipos2.s

tipos3a:	tipos3a.o
	g++ tipos3a.o -o tipos3a

tipos3a.o:	tipos3a.s
	as -g -o tipos3a.o tipos3a.s

tipos3b:	tipos3b.o
	g++ tipos3b.o -o tipos3b

tipos3b.o:	tipos3b.s
	as -g -o tipos3b.o tipos3b.s

clean:
	rm tipos2.o tipos2 tipos3a.o tipos3a tipos3b.o tipos3b